# -*- coding: utf-8 -*-
# Created by Nicolae Gaidarji at 24.04.2020

from datetime import date

data_curenta = date.today()
data_formatata = data_curenta.strftime("%Y%m%d")

rt_ui_default = '<alegeti operatiunea>'
version_nr = 4
app_nr2_version = data_formatata
CompanyName = 'Unisim-Soft'
FileDescription = 'Server FP'
InternalName = 'Server_FP'
OriginalFilename = 'Server_FP'
ProductName = OriginalFilename
version_app = f'V {app_nr2_version}'

DATETIME_FORMAT = "%d.%m.%Y %H:%M"


class LOG_CONST:
    FP_Log = ' FiscalPrinter'
    name_log = '_FP_Server.log'

    LOGSavePath = 'LOG\\'

    START_APP = 'Run Application'
    CLOSE_APP = 'Close Application'
    ERRORUnknown = ' Unknown error'

    Error = 'ERROR'
    Info = 'INFO'
    Warning_ = 'WARNING'
    pass


class SYSVal:
    SLEEP_CMD = 15


LIST_ERR = {
    '-100001': 'ERR_IO General error in fiscal device: In - out error( cannot read or write ) ',
    '-100002': 'ERR_CHECKSUM General error in fiscal device: Wrong checksum',
    '-100003': 'ERR_END_OF_DATA General error in fiscal device: No more data',
    '-100004': 'ERR_NOTFOUND General error in fiscal device: The element is not found',
    '-100005': 'ERR_NO_RECORDS General error in fiscal device: There are no records found',
    '-100006': 'ERR_ABORTED General error in fiscal device: The operation is aborted',
    '-100007': 'ERR_WRONG_MODE Wrong mode( standart, training...) is selected.',

    '-100100': 'ERR_FM_BUSY Fiscal memory error: Fiscal memory is busy',
    '-100101': 'ERR_FM_FAILURE Fiscal memory error: Fiscal memory failure. Could not read or write',
    '-100102': 'ERR_FM_WRITE_PROTECTED Fiscal memory error: Forbidden write in fiscal memory',
    '-100103': 'ERR_FM_WRONG_ADDRESS Fiscal memory error: Wrong address in fiscal memory',
    '-100104': 'ERR_FM_WRONG_SIZE Fiscal memory error: Wrong size in fiscal memory',
    '-100105': 'ERR_FM_NOT_CONNECTED Fiscal memory error: Fiscal memory is not connected',
    '-100106': 'ERR_FM_WRONG_CHECK_SUM Fiscal memory error: Wrong checksum in fiscal memory( invalid data )',
    '-100107': 'ERR_FM_BLOCK_IS_EMPTY Fiscal memory error: Empty block in fiscal memory',
    '-100108': 'ERR_FM_MAX_NUMBER Fiscal memory error: Maximum number of block in fiscal memory',
    '-100109': 'ERR_FM_WRONG_RANGE Fiscal memory error: Wrong range in fiscal memory',
    '-100110': 'ERR_FM_EMPTY_RANGE Fiscal memory error: Empty range in fiscal memory',
    '-100111': 'ERR_FM_NEW_MODULE Fiscal memory error: New module in fiscal memory',
    '-100112': 'ERR_FM_NOT_EMPTY Fiscal memory error: Fiscal memory is not empty',
    '-100113': 'ERR_FM_NOT_EQUAL Fiscal memory error: Fiscal memory is not equal',
    '-100114': 'ERR_FM_FULL Fiscal memory error: Fiscal memory is full',
    '-100115': 'ERR_FM_NEED_UPDATE Fiscal memory error: Fiscal memory needs update',
    '-100116': 'ERR_FM_BLOCKED Fiscal memory error: Fiscal memory is blocked',

    '-100400': 'ERR_LTP_VCCERR Line thermal printer mechanism error: Power supply error ( 3,3 V )',
    '-100401': 'ERR_LTP_SVPERR Line thermal printer mechanism error: Power supply error ( 24V or 8V )',

    '-100402': 'ERR_LTP_STHERR Line thermal printer mechanism error: Head overheating',
    '-100403': 'ERR_LTP_PESENS Line thermal printer mechanism error: Paper end',
    '-100404': 'ERR_LTP_HDSENS Line thermal printer mechanism error: Cover is open',
    '-100405': 'ERR_LTP_NESENS Line thermal printer mechanism error: Near paper end',
    '-100406': 'ERR_LTP_MKSENS Line thermal printer mechanism error: Mark sensor - not used',
    '-100407': 'ERR_LTP_CUTERR Line thermal printer mechanism error: Cutter error',
    '-100408': 'ERR_LTP_PR_ERR Line thermal printer mechanism error: Not used',
    '-100409': 'ERR_LTP_PR_BUSY Line thermal printer mechanism error: Not used',
    '-100410': 'ERR_LTP_BZLPDEC Line thermal printer mechanism error: Not used',
    '-100411': 'ERR_LTP_BZLCLMP Line thermal printer mechanism error: Not used',
    '-100412': 'ERR_LTP_CHARGE_MODE Line thermal printer mechanism error: Not used',
    '-100413': 'ERR_LTP_INZERR_MODE Line thermal printer mechanism error: Not used',
    '-100414': 'ERR_LTP_MOTOR_OVERRUN Printer on time is overrun.',

    '-100500': 'ERR_PROGRAM_SELF_CHECK_ERROR System error: Memory structure error',
    '-100501': 'ERR_SRAM_ERROR System error: Error in RAM',
    '-100502': 'ERR_FLASH_ERROR System error: Flash memory error',
    '-100503': 'ERR_SDCARD_ERROR System error: SD card error',
    '-100504': 'ERR_INVALID_MSG_FILE System error: Invalid message file',
    '-100505': 'ERR_FM_ERROR System error: Fiscal memory error( could not write or read )',
    '-100506': 'ERR_NO_RAM_BATTERY System error: No RAM battery',
    '-100507': 'ERR_SAM_ERROR System error: SAM module error',
    '-100508': 'ERR_RTC_ERROR System error: Real time clock error',
    '-100509': 'ERR_PROGRAM_EXRAM_CHECK_ERROR System error: Memory error',
    '-100510': 'ERR_SDCARD_WRONG_SIZE System error: The size of SD card is wrong.',

    '-101000': 'ERR_NO_HEAP_MEMORY Common logical error: No heap memory( cannot allocate memory for operation )',
    '-101001': 'ERR_FILE_MANIPULATE Common logical error: File manipulate error',
    '-101003': 'ERR_REJECTED Common logical error: Operation is rejected',

    '-101004': 'ERR_BAD_INPUT Common logical error: Bad input. Some of the data or parameters are incorrect',
    '-101005': 'ERR_IAP Common logical error: In Application Programming error',
    '-101006': 'ERR_NOT_POSSIBLE Common logical error: The execution of the operation is not possible',
    '-101007': 'ERR_TIMEOUT Common logical error: Timeout. The time for waiting execution is out',
    '-101008': 'ERR_INVALID_TIME Common logical error: Invalid time',
    '-101009': 'ERR_CANCELLED Common logical error: The operation is cancelled',
    '-101010': 'ERR_INVALID_FORMAT Common logical error: Invalid format',
    '-101011': 'ERR_INVALID_DATA Common logical error: Invalid data',
    '-101012': 'ERR_PARSE_ERROR Common logical error: Data parsing error',
    '-101013': 'ERR_HARDWARE_CONFIGURATION Common logical error: Hardware configuration error',
    '-101014': 'ERR_ACCESS_DENIED ,ERR_ACCESS_DENIED',

    '-101500': 'ERR_NO_UPDATE Update error: No update. The device is up to date',

    '-102000': 'ERR_LOW_BATTERY Battery error: Low battery',
    '-102001': 'ERR_LOW_BATTERY_WARNING Battery error: Low battery warning',
    '-102002': 'ERR_OPER_WRONG_PASSWORD Operator error: Wrong operator password',
    '-102003': 'ERR_IDNUMBER_IS_EMPTY ECR error: ID number is empty',
    '-102004': 'ERR_NOT_FOUND_BLUETOOTH Bluetooth error: Bluetooth is not found',
    '-102005': 'ERR_DISPLAY_DISCONNECTED Display error: Display is not connected',
    '-102006': 'ERR_PRINTER_DISCONNECTED Printer error: Printer is not connected',
    '-102007': 'ERR_SD_NOT_PRESENT SD card error: SD card not present',
    '-102008': 'ERR_SD2_NOT_PRESENT SD card error: SD2 card not present',
    '-102009': 'ERR_VAT_RATES_ARE_EMPTY ECR error: VAT rates is not set.',
    '-102010': 'ERR_HEADER_IS_EMPTY ECR error: Header lines are empty.',

    '-103000': 'ERR_PLUDB_NOT_FOUND PLU database error: PLU database is not found',
    '-103001': 'ERR_PLUDB_PLUCODE_EXISTS PLU database error: PLU code already exists',

    '-103002': 'ERR_PLUDB_BARCODE_EXISTS PLU database error: Barcode already exists',
    '-103003': 'ERR_PLUDB_FULL PLU database error: PLU database is full',
    '-103004': 'ERR_P_HAVE_TURNOVER PLU database error: PLU has turnover',
    '-103005': 'ERR_PLUDB_NAME_EXISTS PLU database error: In the PLU base has an article with same name.',
    '-103006': 'ERR_PLUDB_NAMES_NOT_UNIQUE PLU database error: PLU name is not unique.',
    '-103007': 'ERR_PLUDB_FORMAT_INCOMPATIBLE PLU database error: Database format is not compatible.',
    '-103008': 'ERR_PLUDB_CAN_NOT_OPEN Can`t open the PLU database file',

    '-104000': 'ERR_NEED_Z_REPORT Service operation error: Z report is needed for this operation',
    '-104001': 'ERR_NEED_SERVICE_JUMPER Service operation error: Service jumper is needed for this operation',
    '-104002': 'ERR_NEED_SERVICE_PASSWORD Service operation error: Service password is needed for this operation',
    '-104003': 'ERR_FORBIDEN Service operation error: The operation is forbidden',
    '-104004': 'ERR_NEED_SERVICE_INTERVENTION Service operation error: Service intervention is needed',
    '-104005': 'ERR_NEED_ALL_CLEARING_REPORTS Service operation error: All clearing report is needed.',
    '-104006': 'ERR_Z_REPORT_CLOSED Service operation error: Z report closed.',
    '-104007': 'ERR_NEED_MONTH_REPORT Service operation error: Montly report needed.',
    '-104008': 'ERR_NEED_YEAR_REPORT Service operation error: Year report needed.',
    '-104009': 'ERR_NEED_BACKUP Service operation error: Backup needed.',
    '-104010': 'ERR_NEED_ALL_PAIDOUT ,ERR_NEED_ALL_PAIDOUT',

    '-105000': 'ERR_EJ_NO_RECORDS EJ error: No records in EJ',
    '-105001': 'ERR_CANNOT_ADD_TO_EJ EJ error: Cannot add to EJ',
    '-105002': 'ERR_EJ_WRONG_MAC_RECORD EJ error: SAM module signature error',
    '-105003': 'ERR_EJ_IMMPOSSIBLE_TO_CHK_MAC_RECORD EJ error: Signature key version is changed -> impossible check',
    '-105004': 'ERR_EJ_BAD_RECORDS EJ error: Bad record in EJ',
    '-105005': 'ERR_EJ_CAN_NOT_GENERATE_MAC EJ error: Generate signature error( cannoct generate signature )',
    '-105006': 'ERR_EJ_WRONG_TYPE_TO_SIGN EJ error: Wrong type of document to sign',
    '-105007': 'ERR_EJ_ALREADY_SIGNED EJ error: Document is already signed',
    '-105008': 'ERR_EJ_NOT_FROM_THIS_DEVICE EJ error: EJ is not from this device',
    '-105009': 'ERR_EJ_NEAR_FULL EJ error: EJ is almost full',

    '-105010': 'ERR_EJ_FULL EJ error: EJ is full',
    '-105011': 'ERR_EJ_WRONG_FORMAT EJ error: Wrong format of EJ',
    '-105012': 'ERR_EJ_NOT_READY The electronic journal is not ready.',

    '-106000': 'ERR_R_FIRM_NOTEXIST Client database error: Firm does not exist',
    '-106001': 'ERR_FIRMDB_FIRMCODE_EXISTS Client database error: Firmcode already exists',
    '-106002': 'ERR_FIRMDB_EIK_EXISTS Client database error: EIK already exists',
    '-106003': 'ERR_FIRMDB_FULL Client database error: Firm database is full',
    '-106004': 'ERR_FIRMDB_NOT_FOUND Client database error: Firm database is not found',

    '-107001': 'ERR_INVALID_CERTIFICATE Invalid certificate.',
    '-107002': 'ERR_VALID_CERT_EXISTS Certificate exist.',
    '-107003': 'ERR_CERT_UNPACKING_FAILED Certificate unpack failed.',
    '-107004': 'ERR_CERT_WRONG_PASSWORD Wrong certificate password.',
    '-107005': 'ERR_CERT_FILE_WRITE File write error.',
    '-107006': 'ERR_CERT_FILE_READ File read error.',
    '-107007': 'ERR_CERT_NOT_FOUND Certificate not found.',

    '-108000': 'ERR_R_DISC_NOTEXIST Discount card database error: Discount card does not exist',
    '-108001': 'ERR_DISCDB_DISCCODE_EXISTS Discount card database error: Discount card already exists',
    '-108002': 'ERR_DISCDB_BARCODE_EXISTS Discount card database error: Barcode already exists',
    '-108003': 'ERR_DISCDB_FULL Discount card database error: Discount card database is full',
    '-108004': 'ERR_DISCDB_NOT_FOUND Discount card database error: Discount card not found',

    '-109981': 'ERR_SMARTCARD_NOT_PRESENT Smartcard error: No card in the holder.',
    '-109982': 'ERR_SMARTCARD_CONFIG Smartcard error: Configuration failed',
    '-109983': 'ERR_SMARTCARD_COMMUNICATION Smartcard error: SmartCard communication error.',
    '-109984': 'ERR_SMARTCARD_CARD_FAULT Smartcard error: Supply voltage drop, a VCC over-current detection or '
               'overheating.',

    '-109985': 'ERR_SMARTCARD_MODULE_ERROR Smartcard error: Unexpected response from the applet.',

    '-110000': 'ERR_SAM_INIT SAM module error: SAM init error',
    '-110001': 'ERR_SAM_OPEN_ID_DEV SAM module error: Error, while trying to open SAM module with programmed serial '
               'number',
    '-110002': 'ERR_SAM_OPEN_EMPTY_ID_DEV SAM module error: Opening SAM with empty ID',
    '-110003': 'ERR_SAM_SELECT_FILE SAM module error: SAM select file error',
    '-110004': 'ERR_SAM_INIT_TELEGRAM SAM module error: SAM init telegram error',
    '-110005': 'ERR_SAM_ALREADY_OPEN SAM module error: SAM is already open',
    '-110006': 'ERR_SAM_COMMUNICATION_ERROR SAM module error: SAM communication error',
    '-110010': 'ERR_SAM_BAD_OPERATION SAM module error: Operation execution in SAM module is unsuccessful',
    '-110011': 'ERR_SAM_BAD_GET_TRANS SAM module error: Cannot get last transaction from SAM',
    '-110012': 'ERR_SAM_BAD_PUT_TRANS SAM module error: Cannot register current transaction in SAM',
    '-110013': 'ERR_SAM_BAD_GET_BATCH SAM module error: Cannot get Z-report from SAM',
    '-110014': 'ERR_SAM_BAD_CLOSE_BATCH SAM module error: Cannot register Z-report in SAM',
    '-110021': 'ERR_SAM_TRANS_ALREADY_CLOSED SAM module error: Transaction is closed in SAM -> closing needed',
    '-110022': 'ERR_SAM_BATCH_ALREADY_CLOSED SAM module error: Z-report already closed in SAM -> Z needed',
    '-110023': 'ERR_SAM_UNSENT_Z_OVF SAM module error: Unsent Z-reports -> communication needed',
    '-110024': 'ERR_SAM_OPENED_Z_OVF SAM module error: Overflow in reg -> Z needed',
    '-110025': 'ERR_SAM_NOT_OPENED_Z SAM module error: Not opened( empty ) Z - report -> Z impossible',

    '-110100': 'ERR_DEVICE_COMM_ERROR Device error: Communication error',
    '-110101': 'ERR_DEVICE_WRONG_STRUCT Device error: Wrong struct format',
    '-110102': 'ERR_DEVICE_STFLAG_ACTIVE Device error: ST flag is active',
    '-110103': 'ERR_DEVICE_INVALID_DATA Device error: Invalid data',
    '-110104': 'ERR_DEVICE_NOT_FISCALIZED Device error: Device is not fiscalized',
    '-110105': 'ERR_DEVICE_ALREADY_FISCALIZED Device error: Device is already fiscalized',
    '-110106': 'ERR_DEVICE_IN_SERVICE_MODE Device error: Device is in service mode',
    '-110107': 'ERR_DEVICE_PASSED_SERVICE_DATE Device error: Service date is passed',
    '-110108': 'ERR_DEVICE_DAY_IS_OPEN Device error: Day( shift ) is open',
    '-110109': 'ERR_DEVICE_DAY_IS_CLOSED Device error: Day( shift ) is closed',

    '-110110': 'ERR_DEVICE_WRONG_NUMBERS Device error: Z-report number and shift number are not equal',
    '-110111': 'ERR_DEVICE_ADMIN_ONLY Device error: Only admin has permition',

    '-110200': 'ERR_NAP_OPEN_SESSION NAP server error: Error open session',
    '-110201': 'ERR_NAP_PREPARE_DATA NAP server error: Error preparing data for server',
    '-110202': 'ERR_NAP_SEND_DATA NAP server error: There is unsent data',
    '-110203': 'ERR_NAP_RECV_DATA NAP server error: Receiving data error',
    '-110204': 'ERR_NAP_EMPTY_DATA NAP server error: Empty data',
    '-110205': 'ERR_NAP_NEGATIVE_ANSWER NAP server error: Server negative answer',
    '-110206': 'ERR_NAP_WRONG_ANSWER_FORMAT NAP server error: Wrong answer format',
    '-110207': 'ERR_NAP_HOSTDI_ZERRO NAP server error: Server HOSTDI is zerro',
    '-110208': 'ERR_NAP_EXCEPTION NAP server error: Server exception',
    '-110209': 'ERR_NAP_NOTPERSONALIZED NAP server error: Not registered on server',
    '-110210': 'ERR_NAP_BLOCKED_72H NAP server error: Communication with NAP server is blocked',
    '-110211': 'ERR_NAP_BLOCKED_NO_MODEM_LAN NAP server error: Modem error',
    '-110212': 'ERR_NAP_BUSY NAP server error: NAP is busy',
    '-110213': 'ERR_NAP_REGISTERED NAP server error: Already registered',
    '-110214': 'ERR_NAP_WRONG_PSTYPE NAP server error: Wrong PS type',
    '-110215': 'ERR_NAP_DEREG_ON_SERVER NAP server error: Deregistered in NAP',
    '-110216': 'ERR_NAP_WRONG_IMSI NAP server error: Wrong IMSI number',
    '-110217': 'ERR_NAP_BLOCKED_MAX_ZERRORS NAP server error: Device is blocked( maximum Z-reports )',
    '-110218': 'ERR_NAP_WRONG_FDTYPE NAP server error: Wrong FD( Fiscal device ) type',
    '-110219': 'ERR_NAP_BLOCKED_BY_SERVER NAP server error: The ECR is blocked by server',
    '-110220': 'ERR_NAP_BLOCKED_ERROR_FROM_SERVER NAP server error: The ECR is blocked - server error',
    '-110221': 'ERR_NAP_NO_SERVER_ADDRESS NAP server error: No server address',
    '-110222': 'ERR_NAP_NO_REGISTRATIONS_POSSIBLE NAP server error: Max. registrations reached.',
    '-110223': 'ERR_NAP_INVALID_OPERATOR_INN Invalid INN of the cashier',
    '-110224': 'ERR_NAP_INVALID_SERVER_INN Invalid INN of the server',

    '-110300': 'ERR_WORK_INVALID_FILE Working error: Invalid file',
    '-110301': 'ERR_WORK_INVALID_PARAM Working error: Invalid parameters',

    '-110400': 'ERR_CONNECTION_INIT Connection error: Connection init error',
    '-110401': 'ERR_CONNECTION_WRONG_PARAMS NRA connection error: Wrong parameteres',
    '-110402': 'ERR_CONNECTION_NO_GPRS NRA connection error: No GPRS',

    '-110500': 'ERR_MODEM_CTRL Modem error: error in communication between device and modem',
    '-110501': 'ERR_MODEM_NO_SIM Modem error: No SIM card',
    '-110502': 'ERR_MODEM_PIN Modem error: Wrong PIN of SIM',
    '-110503': 'ERR_MODEM_ATTACH Modem error: Cannot register to mobile network',
    '-110504': 'ERR_MODEM_PPP Modem error: No PPP connection( cannot connect )',
    '-110505': 'ERR_MODEM_CONFIG Modem error: Wrong modem configuration( for example - no programmed apn )',
    '-110506': 'ERR_MODEM_WAIT_INIT Modem error: Modem initializing',
    '-110507': 'ERR_MODEM_NOTREADY Modem error: Modem is not ready',
    '-110508': 'ERR_MODEM_REMOVE_SIM Modem error: Remove SIM card',
    '-110509': 'ERR_MODEM_CELL_FOUND Modem error: Modem found a cell',
    '-110510': 'ERR_MODEM_CELL_NOTFOUND Modem error: Modem does not find a cell',
    '-110511': 'ERR_MODEM_LOT_DAYS_FAIL Modem error: Failed lot days',

    '-110601': 'ERR_MODEM_CONNECT_AP Modem error: Device is not connected to AP( access point )',

    '-110700': 'ERR_NET_DNS_RESOLVE Network error: Cannot resolve address',
    '-110701': 'ERR_NET_SOCKET Network error: Cannot open socket for communication with server',
    '-110702': 'ERR_NET_CONNECTION Network error: Connection error( cannot connect to a server )',
    '-110703': 'ERR_NET_CONFIG Network error: Config error( for example: no server address )',
    '-110704': 'ERR_NET_SOCKET_CONNECTED Network error: Connection socket is already opened',

    '-110705': 'ERR_NET_SSL_ERROR Network error: SSL communication error( something went wrong in cryptographic '
               'protocol )',
    '-110706': 'ERR_NET_HTTP_ERROR Network error: HTTP communication error( something went wrong in http protocol )',

    '-110800': 'ERR_DT_OK Tax terminal error: No error',
    '-110801': 'ERR_DT_UNKNOWN_ID Tax terminal error: Unknown ID',
    '-110802': 'ERR_DT_INVALID_TOKEN Tax terminal error: Invalid token( key from the server )',
    '-110803': 'ERR_DT_PROTOCOL_ERROR Tax terminal error: Protocol error',
    '-110804': 'ERR_DT_UNKNOWN_COMMAND Tax terminal error: The command is unknown',
    '-110805': 'ERR_DT_UNSUPPORTED_COMMAND Tax terminal error: The command is not supported',
    '-110806': 'ERR_DT_INVALID_CONFIGURATION Tax terminal error: Invalid configuration',
    '-110807': 'ERR_DT_SSL_IS_NOT_ALLOWED Tax terminal error: SSL is not allowed',
    '-110808': 'ERR_DT_INVALID_REQUEST_NUMBER Tax terminal error: Invalid request number',
    '-110809': 'ERR_DT_INVALID_RETRY_REQUEST Tax terminal error: Invalid retry request',
    '-110810': 'ERR_DT_CANT_CANCEL_TICKET Tax terminal error: Cannot cancel ticket',
    '-110811': 'ERR_DT_OPEN_SHIFT_TIMEOUT_EXPIRED Tax terminal error: More than 24 hours from shift opening',
    '-110812': 'ERR_DT_INVALID_LOGIN_PASSWORD Tax terminal error: Invalid login name or password',
    '-110813': 'ERR_DT_INCORRECT_REQUEST_DATA Tax terminal error: Incorrect request data',
    '-110814': 'ERR_DT_NOT_ENOUGH_CASH Tax terminal error: Not enough cash',
    '-110815': 'ERR_DT_BLOCKED Tax terminal error: Blocked from server',
    '-110854': 'ERR_DT_SERVICE_TEMPORARILY_UNAVAILABLE Tax terminal error: Service temporarily unavailable',
    '-110855': 'ERR_DT_UNKNOWN_ERROR Tax terminal error: Unknown error',

    '-110900': 'ERR_FN_OK FISCAL NAKOPITEL( RUSSIA ) error: No error',
    '-110901': 'ERR_FN_NEGATIVE_1',
    '-110902': 'ERR_FN_NEGATIVE_2 FISCAL NAKOPITEL( RUSSIA ) error: Wrong state FN',
    '-110903': 'ERR_FN_NEGATIVE_3 FISCAL NAKOPITEL( RUSSIA ) error: FN error',
    '-110904': 'ERR_FN_NEGATIVE_4 FISCAL NAKOPITEL( RUSSIA ) error: CC error( cryptographic co-processor )',

    '-110905': 'ERR_FN_NEGATIVE_5 FISCAL NAKOPITEL( RUSSIA ) error: FN exploatation date expires',
    '-110906': 'ERR_FN_NEGATIVE_6 FISCAL NAKOPITEL( RUSSIA ) error: FN archive is full',
    '-110907': 'ERR_FN_NEGATIVE_7 FISCAL NAKOPITEL( RUSSIA ) error: Invalid date or time',
    '-110908': 'ERR_FN_NEGATIVE_8 FISCAL NAKOPITEL( RUSSIA ) error: No data',
    '-110909': 'ERR_FN_NEGATIVE_9 FISCAL NAKOPITEL( RUSSIA ) error: Wrong command parameters',
    '-110916': 'ERR_FN_NEGATIVE_16 FISCAL NAKOPITEL( RUSSIA ) error: TLV data over limit',
    '-110917': 'ERR_FN_NEGATIVE_17 FISCAL NAKOPITEL( RUSSIA ) error: No connection',
    '-110918': 'ERR_FN_NEGATIVE_18 FISCAL NAKOPITEL( RUSSIA ) error: Full resource ( cryptographic coprocessor )',
    '-110919': 'ERR_FN_NEGATIVE_19 FISCAL NAKOPITEL( RUSSIA ) error: Full resource',
    '-110920': 'ERR_FN_NEGATIVE_20 FISCAL NAKOPITEL( RUSSIA ) error: Full resource for documents for OFD',
    '-110921': 'ERR_FN_NEGATIVE_21 FISCAL NAKOPITEL( RUSSIA ) error: Full resource for waiting transmitting data',
    '-110922': 'ERR_FN_NEGATIVE_22 FISCAL NAKOPITEL( RUSSIA ) error: Shift duration more than 24 hours',
    '-110923': 'ERR_FN_NEGATIVE_23 FISCAL NAKOPITEL( RUSSIA ) error: Wrong time difference between two operations',
    '-110932': 'ERR_FN_NEGATIVE_32 FISCAL NAKOPITEL( RUSSIA ) error: Data from OFD cannot be received',
    '-110960': 'ERR_FN_NEGATIVE_60 FISCAL NAKOPITEL( RUSSIA ) error: Unknown error',
    '-110961': 'ERR_FN_WRONG_STATE FISCAL NAKOPITEL( RUSSIA ) error: Wrong state FN',
    '-110962': 'ERR_FN_WRONG_NUMBER FISCAL NAKOPITEL( RUSSIA ) error: Wrong number FN',
    '-110971': 'ERR_FN_COMM_NOT_SENT FISCAL NAKOPITEL( RUSSIA ) error: Cannot send',
    '-110972': 'ERR_FN_COMM_NO_RESPONSE FISCAL NAKOPITEL( RUSSIA ) error: No response',
    '-110973': 'ERR_FN_COMM_TIME_OUT FISCAL NAKOPITEL( RUSSIA ) error: Timeout',
    '-110974': 'ERR_FN_COMM_NOT_ENOUGH FISCAL NAKOPITEL( RUSSIA ) error: Not enough',
    '-110975': 'ERR_FN_COMM_INV_LENGTH FISCAL NAKOPITEL( RUSSIA ) error: Invalid length',
    '-110976': 'ERR_FN_COMM_WRONG_CRC FISCAL NAKOPITEL( RUSSIA ) error: Wrong CRC',
    '-110979': 'ERR_FN_COMM_UNKNOWN FISCAL NAKOPITEL( RUSSIA ) error: Unknown communication error',

    '-111000': 'ERR_R_CLEAR Registration mode error: Common error, followed by deliting all data for the command',
    '-111001': 'ERR_R_NOCLEAR Registration mode error: Common error, followed by partly deliting data for the command',
    '-111002': 'ERR_R_SYNTAX Registration mode error: Syntax error. Check the parameters of the command',
    '-111003': 'ERR_R_NPOSSIBLE Registration mode error: Cannot do operation',
    '-111004': 'ERR_R_PLU_NOTEXIST Registration mode error: PLU code was not found',
    '-111005': 'ERR_R_PLU_VAT_DISABLE Registration mode error: Forbidden VAT',
    '-111006': 'ERR_R_PLU_QTY_PRC Registration mode error: Overflow in multiplication of quantity and price',
    '-111007': 'ERR_R_PLU_NO_PRC Registration mode error: PLU has no price',
    '-111008': 'ERR_R_PLU_GRP_RANGE Registration mode error: Group is not in range',
    '-111009': 'ERR_R_PLU_DEP_RANGE Registration mode error: Department is not in range',
    '-111010': 'ERR_R_BAR_NOTEXIST Registration mode error: BAR code does not exist',
    '-111011': 'ERR_R_OVF_TOTAL Registration mode error: Overflow of the PLU turnover',
    '-111012': 'ERR_R_OVF_QTY Registration mode error: Overflow of the PLU quantity',
    '-111013': 'ERR_R_ECR_OVR Registration mode error: ECR daily registers overflow',
    '-111014': 'ERR_R_BILL_TL_OVR Registration mode error: Bill total register overflow',
    '-111015': 'ERR_R_OPEN_BON Registration mode error: Receipt is opened',
    '-111016': 'ERR_R_CLOSED_BON Registration mode error: Receipt is closed',
    '-111017': 'ERR_R_PAY_NOCASH Registration mode error: No cash in ECR',
    '-111018': 'ERR_R_PAY_STARTED Registration mode error: Payment is initiated',
    '-111019': 'ERR_R_OVF_TRZ_BUFF Registration mode error: Maximum number of sales in receipt',
    '-111020': 'ERR_R_NO_TRANSACTIONS Registration mode error: No transactions',
    '-111021': 'ERR_R_NEGATIVE_SUMVAT Registration mode error: Possible negative turnover',
    '-111022': 'ERR_R_PYFOREIGN_HAVERESTO Registration mode error: Foreign payment has change',
    '-111023': 'ERR_R_TRZ_NOT_EXIST Registration mode error: Transaction is not found in the receipt',
    '-111024': 'ERR_R_END_OF_24_HOUR_PERIOD Registration mode error: End of 24 hour blocking',
    '-111025': 'ERR_R_NO_VALID_INVOICE Registration mode error: Invalid invoice range',
    '-111026': 'ERR_R_POS_TERM_CANCELED Registration mode error: Operation is cancelled by operator',
    '-111027': 'ERR_R_POS_TERM_APPROVED Registration mode error: Operation approved by POS',
    '-111028': 'ERR_R_POS_TERM_NOT_APPROVED Registration mode error: Operation is not approved by POS',
    '-111029': 'ERR_R_POS_TERM_CONN_ERR Registration mode error: POS terminal communication error',
    '-111030': 'ERR_R_PLU_QTY_PRC_TOO_LOW Registration mode error: Multiplication of quantity and price is 0',
    '-111031': 'ERR_R_VALUE_TOO_BIG Registration mode error: Value is too big',
    '-111032': 'ERR_R_VALUE_BAD Registration mode error: Value is bad',

    '-111033': 'ERR_R_PRICE_TOO_BIG Registration mode error: Price is too big',
    '-111034': 'ERR_R_PRICE_BAD Registration mode error: Price is bad',
    '-111035': 'ERR_R_ALL_VOID_SELECTED Registration mode error: Operation all void is selected to be executed',
    '-111036': 'ERR_R_ONLY_ALL_VOID_IS_POSSIBLE Registration mode error: Only all void operation is permitted',
    '-111040': 'ERR_R_REST_NOFREESPC_SELLS Registration mode error: Restaurant: There is no free space for other '
               'purchases',
    '-111041': 'ERR_R_REST_NOFREESPCFORNEWACNT Registration mode error: Restaurant: There is no free space '
               'for new acount',
    '-111042': 'ERR_R_REST_ACCOUNT_IS_OPENED Registration mode error: Restaurant: Account is already opened',
    '-111043': 'ERR_R_REST_WRONG_INDEX Registration mode error: Restaurant: Wrong index',
    '-111044': 'ERR_R_REST_ACNT_IS_NOTFOUND Registration mode error: Restaurant: Account is not found',
    '-111045': 'ERR_R_REST_NOT_PERMITTED Registration mode error: Restaurant: Not permitted( only for admins )',
    '-111046': 'ERR_R_OPEN_NONFISCALBON Registration mode error: non-fiscal receipt is opened',
    '-111047': 'ERR_R_OPEN_FISCALBON Registration mode error: fiscal receipt is opened',
    '-111048': 'ERR_R_BUYERS_TIN_IS_ENTERED Registration mode error: Buyers TIN is already entered',
    '-111049': 'ERR_R_BUYERS_TIN_IS_NOT_ENTERED Registration mode error: Buyers TIN is not entered',
    '-111050': 'ERR_R_PAY_NOT_STARTED Registration mode error: Payment is not initiated',
    '-111051': 'ERR_R_BON_TYPE_MISMATCH Registration mode error: Reeipt type mismatch',
    '-111052': 'ERR_R_REACH_BON_TL_LIMIT Registration mode error: Receipt total limit is reached',
    '-111053': 'ERR_R_CASH_NO_MULT_MIN_COIN Registration mode error: Sum cannot be divided by the minimum coin',
    '-111054': 'ERR_R_PAY_BIG_AMOUNT Registration mode error: Sum must be <= payment amount',
    '-111055': 'ERR_R_PAY_VOUCHER_NEED_INPUT_SUM Registration mode error: Sum of voucher must be entered when '
               'paying with voucher',
    '-111056': 'ERR_R_PAY_VOUCHER_NEED_SURCHARGE',
    '-111057': 'ERR_R_PAY_FOREIGN_DISABLED Registration mode error: Payment with foreign currency is disabled',
    '-111058': 'ERR_R_PAY_FOREIGN_IMPOSSIBLE Registration mode error: Payment with foreign currency is impossible',
    '-111059': 'ERR_R_PAY_FOREIGN_SMALL_AMOUNT Registration mode error: Sum must be bigger or equal to payment amount',
    '-111060': 'ERR_R_SAFE_OPEN_DISABLED Registration mode error: Safe opening is disabled',
    '-111061': 'ERR_R_PAY_FORBIDDEN Registration mode error: Forbidden payment',
    '-111062': 'ERR_R_PERC_KEY_FORBIDDEN Registration mode error: Forbidden key for surcharge/discount',
    '-111063': 'ERR_R_AMOUNT_BIGGER_BILLAMOUNT Registration mode error: Entered sum is bigger than receipt sum',
    '-111064': 'ERR_R_AMOUNT_SMALLER_BILLAMOUNT Registration mode error: Entered sum is smaller than receipt sum',

    '-111065': 'ERR_R_ZERO_BILLAMOUNT Registration mode error: Fiscal printer: Sum of receipt is 0. '
               'Operation void is needed',
    '-111066': 'ERR_R_ALL_VOID_EXECUTED Registration mode error: Fiscal printer: Operation void is executed. '
               'Close receipt is needed',
    '-111067': 'ERR_R_OPEN_STORNOBON Registration mode error: Storno receipt is opened',
    '-111068': 'ERR_R_PAY_ZERO_AMOUNT Registration mode error: Sum is not entered',
    '-111069': 'ERR_R_PLU_PRICETYPE_RANGE Registration mode error: Price type is invalid',
    '-111070': 'ERR_R_PLU_PRICETYPE_LINKED Registration mode error: Linked surcharge is forbidden',
    '-111071': 'ERR_R_PLU_PRICETYPE_NEGATIVE Registration mode error: Negative price is forbidden',
    '-111072': 'ERR_R_MORE_THAN_ONE_VAT Registration mode error: More than 1 VAT in one receipt is not allowed',
    '-111073': 'ERR_R_PINPAD Registration mode error: Pinpad error',
    '-111074': 'ERR_R_WRONG_BUYERS_DATA Registration mode error: Buyer data is wrong',
    '-111075': 'ERR_R_VAT_SYSTEM_DISABLE Registration mode error: Vat system disable.',
    '-111076': 'ERR_R_OPER_NOT_LOGGED_IN Operator not logged in.',
    '-111077': 'ERR_R_WRONG_DATE_FM The receipt date is early on last date in fiscal memory.',
    '-111078': 'ERR_R_CORR_DATA_NOT_ENTERED Correction receipt data is not entered!',
    '-111079': 'ERR_R_FRACTIONAL_QTY Fractional quantity!',
    '-111080': 'ERR_R_OUT_OF_STOCK Registration mode error: Registration mode error: Out of stock',
    '-111081': 'ERR_R_STL_NEEDED Registration mode error: Must pushing of the STL before TL.',
    '-111082': 'ERR_R_PACK_NOTEXIST Package does not exist',
    '-111083': 'ERR_R_PLU_UNIT_NOTEXIST Measuring unit not found',
    '-111084': 'ERR_R_PLU_CATEGORY_NOTEXIST Category not found in the data base',
    '-111085': 'ERR_R_DEP_WRONG_NAME Invalid department name',
    '-111086': 'ERR_R_BANK_TERM_NOT_CONFIGURED Bank terminal not configured',
    '-111087': 'ERR_R_SIGN_PAY_INCORECT Disallowed признак расчета (Russia)',
    '-111088': 'ERR_R_SIGN_INCORRECT Forbidden признак товара',
    '-111089': 'ERR_R_PLU_OVER_MAX_PRC Entered price is bigger than the programmed',
    '-111090': 'ERR_R_PLU_FIX_PRC Fix PLU`s price',
    '-111091': 'ERR_R_SIGN_AGENT_INCORECT Incorect sign agent.',

    '-111500': 'ERR_PINPAD_NONE Pinpad error: No error from pinpad',
    '-111501': 'ERR_PINPAD_GENERAL Pinpad error: General unicreditbulbank icon error',
    '-111502': 'ERR_PINPAD_INVALID_COMMAND Pinpad error: Not valid command or sub command code',
    '-111503': 'ERR_PINPAD_INVALID_PARAM Pinpad error: Invalid parameter',
    '-111504': 'ERR_PINPAD_INVALID_ADDRESS Pinpad error: The address is outside limits',
    '-111505': 'ERR_PINPAD_INVALID_VALUE Pinpad error: The value is outside limits',
    '-111506': 'ERR_PINPAD_INVALID_LENGTH Pinpad error: The length is outside limits',
    '-111507': 'ERR_PINPAD_NOT_PERMIT Pinpad error: The action is not permited in current state',
    '-111508': 'ERR_PINPAD_NO_DATA Pinpad error: There is no data to be returned',
    '-111509': 'ERR_PINPAD_TIMEOUT Pinpad error: Timeout occurs',
    '-111510': 'ERR_PINPAD_INVALID_KEY_NUMBER Pinpad error: Invalid key number',
    '-111511': 'ERR_PINPAD_INVALID_KEY_ATTRIBUTES Pinpad error: Invalid key attributes(usage)',
    '-111512': 'ERR_PINPAD_INVALID_DEVICE Pinpad error: Calling of non-existing device',
    '-111513': 'ERR_PINPAD_NOT_SUPPORT Pinpad error: (Not used in this FW version)',
    '-111514': 'ERR_PINPAD_PIN_LIMIT Pinpad error: Pin entering limit exceed',
    '-111515': 'ERR_PINPAD_FLASH Pinpad error: General error in flash commands',
    '-111516': 'ERR_PINPAD_HARDWARE Pinpad error: General hardware unicreditbulbank error',
    '-111517': 'ERR_PINPAD_INVALID_CRC Pinpad error: Invalid code check (Not used in this FW version)',
    '-111518': 'ERR_PINPAD_CANCEL Pinpad error: The button CANCEL is pressed',
    '-111519': 'ERR_PINPAD_INVALID_SIGNATURE Pinpad error: Invalid signature',
    '-111520': 'ERR_PINPAD_INVALID_HEADER Pinpad error: Invalid data in header',
    '-111521': 'ERR_PINPAD_INVALID_PASSWORD Pinpad error: Incorrect password',
    '-111522': 'ERR_PINPAD_INVALID_KEY_FORMAT Pinpad error: Invalid key format',
    '-111523': 'ERR_PINPAD_SCR Pinpad error: General unicreditbulbank error in smart card reader',
    '-111524': 'ERR_PINPAD_HAL Pinpad error: Error code returned from HAL functions',
    '-111525': 'ERR_PINPAD_INVALID_KEY Pinpad error: Invalid key (may not be present)',
    '-111526': 'ERR_PINPAD_NO_PIN_DATA Pinpad error: The PIN length is less than 4 or bigger than 12',
    '-111527': 'ERR_PINPAD_INVALID_REMINDER Pinpad error: Issuer or ICC key invalid remainder length',
    '-111528': 'ERR_PINPAD_NOT_INIT Pinpad error: Not initialized (Not used in this FW version)',
    '-111529': 'ERR_PINPAD_LIMIT Pinpad error: Limit is reached (Not used in this FW version)',
    '-111530': 'ERR_PINPAD_INVALID_SEQUENCE Pinpad error: Invalid sequence (Not used in this FW version)',
    '-111531': 'ERR_PINPAD_NO_PERMITION Pinpad error: The action is not permitted',
    '-111532': 'ERR_PINPAD_NO_TMK Pinpad error: TMK is not loaded. The action cannot be executed',
    '-111533': 'ERR_PINPAD_INVALID_KEK Pinpad error: Wrong key format',

    '-111534': 'ERR_PINPAD_DUPLICATE_KEY Pinpad error: Duplicated key',
    '-111535': 'ERR_PINPAD_KEYBOARD Pinpad error: General keyboard error',
    '-111536': 'ERR_PINPAD_KEYBOARD_NOT_CALIBRATED Pinpad error: The keyboard is no calibrated.',
    '-111537': 'ERR_PINPAD_KEYBOARD_FAILED Pinpad error: Keyboard bug detected.',
    '-111538': 'ERR_PINPAD_DEVICE_BUSY Pinpad error: The device is busy, try again',
    '-111539': 'ERR_PINPAD_TAMPERED Pinpad error: Device is tampered',
    '-111540': 'ERR_PINPAD_EMSR Pinpad error: Error in encrypted head',
    '-111541': 'ERR_PINPAD_ACCEPT Pinpad error: The button OK is pressed',
    '-111542': 'ERR_PINPAD_INVALID_PAN Pinpad error: Wrong PAN',
    '-111543': 'ERR_PINPAD_NOT_ENOUGH_MEMORY Pinpad error: Out of memory',
    '-111544': 'ERR_PINPAD_EMV Pinpad error: EMV error',
    '-111545': 'ERR_PINPAD_CRYPTOGRAPHY Pinpad error: Cryptographic error',
    '-111546': 'ERR_PINPAD_COMMUNICATION Pinpad error: Communication error',
    '-111547': 'ERR_PINPAD_INVALID_VERSION Pinpad error: Invalid firmware version',
    '-111548': 'ERR_PINPAD_NOPAPER Pinpad error: Printer is out of paper',
    '-111549': 'ERR_PINPAD_OVERHEATED Pinpad error: Printer is overheated',
    '-111550': 'ERR_PINPAD_NOT_CONNECTED Pinpad error: Device is not connected',
    '-111551': 'ERR_PINPAD_USE_CHIP Pinpad error: Use the chip reader',
    '-111552': 'ERR_PINPAD_END_DAY Pinpad error: End the day first',
    '-111554': 'ERR_PINPAD_BOR_ERR Pinpad error: Error from Borica',
    '-111555': 'ERR_PINPAD_NO_CONN Pinpad error: No connection with pinpad',
    '-111556': 'ERR_PINPAD_ECR Pinpad error: Success in pinpad, unsuccess in ECR',
    '-111557': 'ERR_PINPAD_NOT_CONF Pinpad error: Not configured connection between fiscal device and PinPad',
    '-111558': 'ERR_PINPAD_SAME_TRANS Pinpad error: The last transactions are equals or connection '
               'is interrupted - try again.',
    '-111559': 'ERR_PINPAD_RECEIPT',
    '-111560': 'ERR_PINPAD_FP_TRANS Pinpad error: Unknown result of the transaction between fiscal device and PinPad',
    '-111561': 'ERR_PINPAD_NOT_CONF_TYPE Pinpad error: Pinpad type not configured',
    '-111700': 'ERR_PINPAD_INV_AMOUNT Pinpad error: Invalid ammount.',
    '-111701': 'ERR_PINPAD_TRN_NOT_FOUND Pinpad error: Transaction not found.',
    '-111702': 'ERR_PINPAD_FILE_EMPTY Pinpad error: The file is empty.',

    '-111800': 'ERR_SCALE_NOT_RESPOND ,ERR_SCALE_NOT_RESPOND',
    '-111801': 'ERR_SCALE_NOT_CALCULATED ,ERR_SCALE_NOT_CALCULATED',
    '-111802': 'ERR_SCALE_WRONG_RESPONSE ,ERR_SCALE_WRONG_RESPONSE',
    '-111803': 'ERR_SCALE_ZERO_WEIGHT ,ERR_SCALE_ZERO_WEIGHT',
    '-111804': 'ERR_SCALE_NEGATIVE_WEIGHT ,ERR_SCALE_NEGATIVE_WEIGHT',
    '-111805': 'ERR_SCALE_T_WRONG_INTF ,ERR_SCALE_T_WRONG_INTF',
    '-111806': 'ERR_SCALE_T_CONNECT ,ERR_SCALE_T_CONNECT',
    '-111807': 'ERR_SCALE_SEND ,ERR_SCALE_SEND',
    '-111808': 'ERR_SCALE_RECEIVE ,ERR_SCALE_RECEIVE',
    '-111809': 'ERR_SCALE_FILE_GENERATE ,ERR_SCALE_FILE_GENERATE',
    '-111810': 'ERR_SCALE_NOT_CONFIG ,ERR_SCALE_NOT_CONFIG',

    '-112000': 'ERR_FP_INVALID_COMMAND Fiscal printer error: Fiscal printer invalid command',
    '-112001': 'ERR_FP_INVALID_SYNTAX Fiscal printer error: Fiscal printer command invalid syntax',
    '-112002': 'ERR_FP_COMMAND_NOT_PERMITTED Fiscal printer error: Command is not permitted',
    '-112003': 'ERR_FP_OVERFLOW Fiscal printer error: Register overflow',
    '-112004': 'ERR_FP_WRONG_DATE_TIME Fiscal printer error: Wrong date/time',
    '-112005': 'ERR_FP_NEEDED_MODE_PC Fiscal printer error: PC mode is needed',
    '-112006': 'ERR_FP_NO_PAPER Fiscal printer error: No paper',
    '-112007': 'ERR_FP_COVER_IS_OPEN Fiscal printer error: Cover is open',
    '-112008': 'ERR_FP_PRINTER_FAILURE Fiscal printer error: Printing mechanism error',

    '-112100': 'ERR_FP_SYNTAX_PARAM_BEGIN _ERR_FP_SYNTAX_PARAM_BEGIN',
    '-112101': 'ERR_FP_SYNTAX_PARAM_1 Invalid syntax of parameter 1.',
    '-112102': 'ERR_FP_SYNTAX_PARAM_2 Invalid syntax of parameter 2.',
    '-112103': 'ERR_FP_SYNTAX_PARAM_3 Invalid syntax of parameter 3.',
    '-112104': 'ERR_FP_SYNTAX_PARAM_4 Invalid syntax of parameter 4.',
    '-112105': 'ERR_FP_SYNTAX_PARAM_5 Invalid syntax of parameter 5.',
    '-112106': 'ERR_FP_SYNTAX_PARAM_6 Invalid syntax of parameter 6.',

    '-112107': 'ERR_FP_SYNTAX_PARAM_7 Invalid syntax of parameter 7.',
    '-112108': 'ERR_FP_SYNTAX_PARAM_8 Invalid syntax of parameter 8.',
    '-112109': 'ERR_FP_SYNTAX_PARAM_9 Invalid syntax of parameter 9.',
    '-112110': 'ERR_FP_SYNTAX_PARAM_10 Invalid syntax of parameter 10.',
    '-112111': 'ERR_FP_SYNTAX_PARAM_11 Invalid syntax of parameter 11.',
    '-112112': 'ERR_FP_SYNTAX_PARAM_12 Invalid syntax of parameter 12.',
    '-112113': 'ERR_FP_SYNTAX_PARAM_13 Invalid syntax of parameter 13.',
    '-112114': 'ERR_FP_SYNTAX_PARAM_14 Invalid syntax of parameter 14.',
    '-112115': 'ERR_FP_SYNTAX_PARAM_15 Invalid syntax of parameter 15.',
    '-112116': 'ERR_FP_SYNTAX_PARAM_16 Invalid syntax of parameter 16.',
    '-112199': 'ERR_FP_SYNTAX_PARAM_END _ERR_FP_SYNTAX_PARAM_END',

    '-112200': 'ERR_FP_BAD_PARAM_BEGIN _ERR_FP_BAD_PARAM_BEGIN',
    '-112201': 'ERR_FP_BAD_PARAM_1 Bad value of parameter 1.',
    '-112202': 'ERR_FP_BAD_PARAM_2 Bad value of parameter 2.',
    '-112203': 'ERR_FP_BAD_PARAM_3 Bad value of parameter 3.',
    '-112204': 'ERR_FP_BAD_PARAM_4 Bad value of parameter 4.',
    '-112205': 'ERR_FP_BAD_PARAM_5 Bad value of parameter 5.',
    '-112206': 'ERR_FP_BAD_PARAM_6 Bad value of parameter 6.',
    '-112207': 'ERR_FP_BAD_PARAM_7 Bad value of parameter 7.',
    '-112208': 'ERR_FP_BAD_PARAM_8 Bad value of parameter 8.',
    '-112209': 'ERR_FP_BAD_PARAM_9 Bad value of parameter 9.',
    '-112210': 'ERR_FP_BAD_PARAM_10 Bad value of parameter 10.',
    '-112211': 'ERR_FP_BAD_PARAM_11 Bad value of parameter 11.',
    '-112212': 'ERR_FP_BAD_PARAM_12 Bad value of parameter 12.',
    '-112213': 'ERR_FP_BAD_PARAM_13 Bad value of parameter 13.',
    '-112214': 'ERR_FP_BAD_PARAM_14 Bad value of parameter 14.',
    '-112215': 'ERR_FP_BAD_PARAM_15 Bad value of parameter 15.',
    '-112216': 'ERR_FP_BAD_PARAM_16 Bad value of parameter 16.',
    '-112299': 'ERR_FP_BAD_PARAM_END _ERR_FP_BAD_PARAM_END',

    '-112900': 'ERR_RANGE_EM_BEGIN _ERR_RANGE_EM_BEGIN',
    '-112999': 'ERR_RANGE_EM_END _ERR_RANGE_EM_END',

    '-113000': 'ERR_FLASH_WRONG_ID Flash memory error: Reading ID error',
    '-113001': 'ERR_FLASH_WRONG_SIZE Flash memory error: Sector size error',

    '-114000': 'ERR_POS_TERM_CHAN_CLOSED POS- terminal error: Communication channel is closed',

    '-114998': 'ERR_CM_WRONG_ID_NUMBERS Crypto module error: Wrong ID numbers',
    '-114999': 'ERR_CM_UNEXPECTED_RESPONSE Crypto module еррор: Unexpected response',
    '-115000': 'ERR_CM_DISCONNECTED Crypto module еррор: CM is disconnected',
    '-115001': 'ERR_CM_COM_ERROR Crypto module еррор: Communication error',
    '-115002': 'ERR_CM_COM_TIMEOUT Crypto module еррор: Timeout',
    '-116000': 'ERR_RANGE_CM_BEGIN Crypto module еррор: Crypto module errors range begin.',
    '-117999': 'ERR_RANGE_CM_END Crypto module еррор: Crypto module errors range end.',

    '-118000': 'ERR_ECRSRV_NO_SOCKET_OPENED ECR server error: The connection socket is not open',
    '-118001': 'ERR_ECRSRV_SET_IS_NOT_TAKEN ECR server error: The set for this command is not opened',
    '-118002': 'ERR_ECRSRV_WRONG_PARAM ECR server error: Wrong parameter',
    '-118003': 'ERR_ECRSRV_NOT_SEND ECR server error: Socket send error. Could not send data to server',
    '-118004': 'ERR_ECRSRV_RECV_TMOUT ECR server error: Receiving timeout. No data is receivec on time',
    '-118005': 'ERR_ECRSRV_SOCKET_CLOSED ECR server error: Socket is closed',
    '-118006': 'ERR_ECRSRV_UNKNOWN ECR server error: Unknown state',
    '-118007': 'ERR_ECRSRV_FORBIDEN ECR server error: Forbidden operation',

    '-119000': 'ERR_PACKDB_PACKCODE_EXISTS PACK database error: PACK code already exists',
    '-119001': 'ERR_PACKDB_FULL PACK database error: PACK database is full',

    '-119002': 'ERR_PACKDB_HAVE_TURNOVER PACK database error: PACK has turnover',
    '-119003': 'ERR_PACKDB_NAME_EXISTS PACK database error: In the PACK base has an article with same name.',
    '-119004': 'ERR_PACKDB_NAMES_NOT_UNIQUE PACK database error: PACK name is not unique.',
    '-119005': 'ERR_PACKDB_CAN_NOT_OPEN Can`t open the PACK database file',

    '-170000': 'ERR_USB_HOST_INIT USB error: Host init error',
    '-170001': 'ERR_USB_NO_DEVICE USB error: No device',
    '-170002': 'ERR_USB_NO_FILESYSTEM USB error: No filesystem',
    '-170003': 'ERR_USB_FILE_OPEN USB error: File open error',
    '-170004': 'ERR_USB_FILE_COPY USB error: File copy error',
    '-170005': 'ERR_FILE_UNPACK USB error: File unpack error',

    '-200001': 'ERR_Server_FP: cmd 119, not found select option'
}
