# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis\form_UI_allFP.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(830, 537)
        self.tab_Box = QtGui.QTabWidget(Form)
        self.tab_Box.setEnabled(True)
        self.tab_Box.setGeometry(QtCore.QRect(5, 5, 819, 521))
        self.tab_Box.setMinimumSize(QtCore.QSize(819, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tab_Box.setFont(font)
        self.tab_Box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_Box.setTabPosition(QtGui.QTabWidget.North)
        self.tab_Box.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_Box.setDocumentMode(False)
        self.tab_Box.setObjectName(_fromUtf8("tab_Box"))
        self.tb_Setting = QtGui.QWidget()
        self.tb_Setting.setObjectName(_fromUtf8("tb_Setting"))
        self.gridLayoutWidget = QtGui.QWidget(self.tb_Setting)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 491))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 4)
        self.cb_Port = QtGui.QComboBox(self.gridLayoutWidget)
        self.cb_Port.setObjectName(_fromUtf8("cb_Port"))
        self.gridLayout.addWidget(self.cb_Port, 3, 1, 1, 1)
        self.cb_Baud = QtGui.QComboBox(self.gridLayoutWidget)
        self.cb_Baud.setObjectName(_fromUtf8("cb_Baud"))
        self.gridLayout.addWidget(self.cb_Baud, 3, 3, 1, 1)
        self.ln_IPAddress = QtGui.QLineEdit(self.gridLayoutWidget)
        self.ln_IPAddress.setMaxLength(999999999)
        self.ln_IPAddress.setObjectName(_fromUtf8("ln_IPAddress"))
        self.gridLayout.addWidget(self.ln_IPAddress, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 4)
        self.cb_Model = QtGui.QComboBox(self.gridLayoutWidget)
        self.cb_Model.setObjectName(_fromUtf8("cb_Model"))
        self.gridLayout.addWidget(self.cb_Model, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.cb_TypeConnection = QtGui.QComboBox(self.gridLayoutWidget)
        self.cb_TypeConnection.setObjectName(_fromUtf8("cb_TypeConnection"))
        self.gridLayout.addWidget(self.cb_TypeConnection, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 2, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.ln_OperatorPass = QtGui.QLineEdit(self.gridLayoutWidget)
        self.ln_OperatorPass.setMaxLength(4)
        self.ln_OperatorPass.setObjectName(_fromUtf8("ln_OperatorPass"))
        self.gridLayout.addWidget(self.ln_OperatorPass, 11, 1, 1, 1)
        self.cb_OperatoName = QtGui.QComboBox(self.gridLayoutWidget)
        self.cb_OperatoName.setObjectName(_fromUtf8("cb_OperatoName"))
        self.gridLayout.addWidget(self.cb_OperatoName, 10, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bt_OpenConn = QtGui.QPushButton(self.gridLayoutWidget)
        self.bt_OpenConn.setStyleSheet(_fromUtf8("padding: 5px;\n"
"font: 75 12pt \"Times New Roman\";\n"
"font-weight: bold;"))
        self.bt_OpenConn.setObjectName(_fromUtf8("bt_OpenConn"))
        self.gridLayout_2.addWidget(self.bt_OpenConn, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.bt_CloseConn = QtGui.QPushButton(self.gridLayoutWidget)
        self.bt_CloseConn.setStyleSheet(_fromUtf8("padding: 5px;\n"
"font: 75 12pt \"Times New Roman\";\n"
"font-weight: bold;"))
        self.bt_CloseConn.setObjectName(_fromUtf8("bt_CloseConn"))
        self.gridLayout_2.addWidget(self.bt_CloseConn, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 0, 1, 4)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 10, 2, 1, 2)
        self.la_CurentOperator = QtGui.QLabel(self.gridLayoutWidget)
        self.la_CurentOperator.setAlignment(QtCore.Qt.AlignCenter)
        self.la_CurentOperator.setObjectName(_fromUtf8("la_CurentOperator"))
        self.gridLayout.addWidget(self.la_CurentOperator, 11, 2, 1, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.bt_SaveOperator = QtGui.QPushButton(self.gridLayoutWidget)
        self.bt_SaveOperator.setStyleSheet(_fromUtf8("padding: 5px;\n"
"font: 75 12pt \"Times New Roman\";\n"
"font-weight: bold;"))
        self.bt_SaveOperator.setObjectName(_fromUtf8("bt_SaveOperator"))
        self.gridLayout_3.addWidget(self.bt_SaveOperator, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 12, 0, 1, 4)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 7, 0, 1, 4)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 9, 0, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 13, 0, 1, 4)
        self.tab_Box.addTab(self.tb_Setting, _fromUtf8(""))
        self.tb_Info = QtGui.QWidget()
        self.tb_Info.setEnabled(True)
        self.tb_Info.setObjectName(_fromUtf8("tb_Info"))
        self.tab_Box.addTab(self.tb_Info, _fromUtf8(""))
        self.tb_Reports = QtGui.QWidget()
        self.tb_Reports.setObjectName(_fromUtf8("tb_Reports"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tb_Reports)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 811, 491))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.bt_ReportX = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.bt_ReportX.setObjectName(_fromUtf8("bt_ReportX"))
        self.gridLayout_4.addWidget(self.bt_ReportX, 3, 1, 1, 1)
        self.bt_ReportZ = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.bt_ReportZ.setObjectName(_fromUtf8("bt_ReportZ"))
        self.gridLayout_4.addWidget(self.bt_ReportZ, 3, 0, 1, 1)
        self.bt_ReportDept = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.bt_ReportDept.setObjectName(_fromUtf8("bt_ReportDept"))
        self.gridLayout_4.addWidget(self.bt_ReportDept, 4, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 0, 0, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 2, 0, 1, 2)
        self.te_ResultReport = QtGui.QTextEdit(self.gridLayoutWidget_4)
        self.te_ResultReport.setObjectName(_fromUtf8("te_ResultReport"))
        self.gridLayout_4.addWidget(self.te_ResultReport, 7, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 6, 0, 1, 2)
        self.la_ReportsHeader = QtGui.QLabel(self.gridLayoutWidget_4)
        self.la_ReportsHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.la_ReportsHeader.setObjectName(_fromUtf8("la_ReportsHeader"))
        self.gridLayout_4.addWidget(self.la_ReportsHeader, 1, 0, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 5, 0, 1, 2)
        self.tab_Box.addTab(self.tb_Reports, _fromUtf8(""))
        self.tb_Utility = QtGui.QWidget()
        self.tb_Utility.setObjectName(_fromUtf8("tb_Utility"))
        self.tab_Box.addTab(self.tb_Utility, _fromUtf8(""))
        self.tb_Logs = QtGui.QWidget()
        self.tb_Logs.setObjectName(_fromUtf8("tb_Logs"))
        self.tab_Box.addTab(self.tb_Logs, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tab_Box.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_6.setText(_translate("Form", "Communication", None))
        self.label_3.setText(_translate("Form", "Port Serial", None))
        self.label_7.setText(_translate("Form", "Operator", None))
        self.label.setText(_translate("Form", "Model FP", None))
        self.label_2.setText(_translate("Form", "Tip Conection", None))
        self.label_5.setText(_translate("Form", "IP Address", None))
        self.label_4.setText(_translate("Form", "Baud Rate", None))
        self.ln_OperatorPass.setText(_translate("Form", "0000", None))
        self.label_9.setText(_translate("Form", "Operator Pass", None))
        self.bt_OpenConn.setText(_translate("Form", "Open Connection", None))
        self.bt_CloseConn.setText(_translate("Form", "Close Connection", None))
        self.label_8.setText(_translate("Form", "Operator Name", None))
        self.label_10.setText(_translate("Form", "Current Operator:", None))
        self.la_CurentOperator.setText(_translate("Form", "Operator Name", None))
        self.bt_SaveOperator.setText(_translate("Form", "Save Operator", None))
        self.tab_Box.setTabText(self.tab_Box.indexOf(self.tb_Setting), _translate("Form", "Settings", None))
        self.tab_Box.setTabText(self.tab_Box.indexOf(self.tb_Info), _translate("Form", "Info Device", None))
        self.bt_ReportX.setText(_translate("Form", "Report X", None))
        self.bt_ReportZ.setText(_translate("Form", "Report Z", None))
        self.bt_ReportDept.setText(_translate("Form", "Report Departament", None))
        self.label_11.setText(_translate("Form", "Result:", None))
        self.la_ReportsHeader.setText(_translate("Form", "Sett Communication FP and Operator  ", None))
        self.tab_Box.setTabText(self.tab_Box.indexOf(self.tb_Reports), _translate("Form", "Reports", None))
        self.tab_Box.setTabText(self.tab_Box.indexOf(self.tb_Utility), _translate("Form", "Utility", None))
        self.tab_Box.setTabText(self.tab_Box.indexOf(self.tb_Logs), _translate("Form", "Logs", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

